on:
  push:
     branches:
       - main

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container:
      image: vvanhoef/r-min-bookdown:0.3
    steps:
      - uses: actions/checkout@v1
      - name: Render Book
        run: Rscript -e 'rmarkdown::render("index.Rmd"")'
      - uses: actions/upload-artifact@v1
        with:
          name: index.html
          path: index.html